override-remove:
  - moby-engine
  - moby-filesystem
  - containerd
  - docker-cli
  - zincati
  - nano
  - nano-default-editor
packages:
  - container-selinux
  - podman-docker
  - pciutils
  - usbutils
  # - vim-default-editor
  # - vim-data
  - screen
  - tftp-server
  - tree
  - mesa-vulkan-drivers
  - vulkan-loader 
  - vulkan-tools
  - sing-box
  - bird
  - bind-utils
  - python3-requests
  - python3-virtualenvwrapper
  # - python3.13-devel
  - python3-devel
  - zsh
  - java-latest-openjdk
  - java-latest-openjdk-devel
  - golang
  - nodejs-npm
  - clang
  - llvm
  - cmake
  - make
  - unzip
  - zip
  - ninja-build
  - chromium
  - gtk3-devel
  - android-tools
